# Generated by Django 5.0.1 on 2024-01-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='D:/Django/Chat_App/chatapp/static/img/profile.png', null=True, upload_to='img'),
        ),
    ]
