# Generated by Django 5.0.1 on 2024-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
