# Generated by Django 5.0.1 on 2024-01-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_profile_last_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_message_timestamp',
        ),
    ]
