# Generated by Django 5.0.1 on 2024-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_profile_last_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
