# Generated by Django 5.0.1 on 2024-01-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_chatmessage_encryption_iv_chatmessage_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='encryption_iv',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='encryption_key',
        ),
    ]
