# Generated by Django 5.0.1 on 2024-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_chatmessage_encryption_iv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
