# Generated by Django 5.0.1 on 2024-01-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatmessage_encryption_iv_chatmessage_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
