# Generated by Django 5.0.1 on 2024-01-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_chatmessage_encryption_iv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='encryption_iv',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='encryption_key',
        ),
    ]
