# Generated by Django 5.0.1 on 2024-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_chatmessage_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='encrypted_body',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
