# Generated by Django 5.0.1 on 2024-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_remove_chatmessage_encrypted_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
