# Generated by Django 5.0.1 on 2024-01-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_chatmessage_body_chatmessage_encrypted_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='encrypted_body',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
