# Generated by Django 5.0.1 on 2024-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_remove_chatmessage_body_chatmessage_ebody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='ebody',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
