# Generated by Django 5.0.1 on 2024-01-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_chatmessage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='key',
            field=models.BinaryField(blank=True),
        ),
    ]
