# Generated by Django 5.0.1 on 2024-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_remove_chatmessage_body_chatmessage_ebody'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ebody',
            field=models.TextField(blank=True),
        ),
    ]
