# Generated by Django 5.0.1 on 2024-01-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_chatmessage_body_alter_chatmessage_ebody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='ebody',
        ),
    ]
