# Generated by Django 5.0.1 on 2024-01-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_remove_chatmessage_ebody'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(default=b'12345670'),
        ),
    ]
