# Generated by Django 5.0.1 on 2024-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_alter_chatmessage_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(default=b'[\x0c\x9e\xc6iB\xb0\xbe\x93\xc5\xab\xf0\x1f\r\xae\x8c'),
        ),
    ]
