# Generated by Django 5.0.1 on 2024-01-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_alter_chatmessage_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='body',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ebody',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(default=b'\xd6\xb2[w\xecC\xddUi5r\xa8\x0f\xd7e\xcf'),
        ),
    ]
