# Generated by Django 5.0.1 on 2024-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_remove_chatmessage_body_chatmessage_ebody_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='ebody',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(default=b'D\xc3\xce\xfbc\x04B\x06Z_B\xc1\xff\xff\x962'),
        ),
    ]
