# Generated by Django 5.0.1 on 2024-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_rename_ebody_chatmessage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.BinaryField(default=b'q\xea\x92,T\xea\xca0\x95\x12\x9c$Dq\xa1\t'),
        ),
    ]
