# Generated by Django 5.0.1 on 2024-01-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_friend_last_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='last_message_timestamp',
        ),
    ]
