# Generated by Django 5.0.1 on 2024-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_remove_friend_last_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
