# Generated by Django 5.0.1 on 2024-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_friend_last_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='last_message_timestamp',
        ),
        migrations.AddField(
            model_name='friend',
            name='last_message',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
