# Generated by Django 5.0.1 on 2024-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0051_remove_friend_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='body',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ebody',
            field=models.BinaryField(blank=True),
        ),
    ]
