# Generated by Django 5.0.1 on 2024-01-12 12:11

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0054_alter_chatmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=pgcrypto.fields.EncryptedTextField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
