# Generated by Django 5.0.1 on 2024-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0055_alter_chatmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
