# Generated by Django 5.0.1 on 2024-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0056_alter_chatmessage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='body',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encrypted_body',
            field=models.BinaryField(blank=True),
        ),
    ]
