# Generated by Django 5.0.1 on 2024-01-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0057_remove_chatmessage_body_chatmessage_encrypted_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='encrypted_body',
            new_name='body',
        ),
    ]
