# Generated by Django 5.0.1 on 2024-01-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0058_rename_encrypted_body_chatmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ebody',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
