# Generated by Django 5.0.1 on 2024-01-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0061_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
    ]
