# Generated by Django 5.0.1 on 2024-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0063_chatmessage_sender_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_deleted',
        ),
    ]
