# Generated by Django 5.0.1 on 2024-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0064_remove_chatmessage_sender_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
